Repository francescarpi/buffon.nvim, pull requests merged in 2025-05, with the labels that each got.

#94 refactor: set hl color if is not already defined using the neovim api
  .github/workflows/default.yml
  README.md
  imgs/hlgroups.png
  lua/buffon/config.lua
Labels: documentation, enhancement

#95 release: v2025-05-04
  .github/workflows/default.yml
  README.md
  imgs/hlgroups.png
  lua/buffon/config.lua
Labels: release

#99 fix: windows path backslashes can cause trouble
  lua/buffon/buffer.lua
Labels: enhancement

#100 feat: return ctrl in setup function
  lua/buffon/init.lua
Labels: enhancement

#101 feat: allow empty lhs
  lua/buffon/maincontroller.lua
Labels: enhancement

#113 feat: allows ignoring buffers using regular expressions
  README.md
  lua/buffon/bufferslist.lua
  lua/buffon/config.lua
  tests/bufferslist_spec.lua
  tests/config_spec.lua
Labels: enhancement

#116 fix: increment the z-index to avoid problems with treesitter-context
  lua/buffon/ui/window.lua
Labels: bug

#110 feat: sort buffers by loaded status
  README.md
  lua/buffon/buffer.lua
  lua/buffon/bufferslist.lua
  lua/buffon/config.lua
  lua/buffon/maincontroller.lua
  tests/bufferslist_spec.lua
  tests/config_spec.lua
Labels: enhancement

#120 feat: add option to set default window position
  README.md
  lua/buffon/config.lua
  lua/buffon/ui/mainwindow.lua
  tests/config_spec.lua
Labels: enhancement

#123 feat: place the help window on the opposite side of the main window
  lua/buffon/maincontroller.lua
  lua/buffon/ui/help.lua
Labels: enhancement

#124 release: v2025-05-15
  README.md
  lua/buffon/config.lua
  lua/buffon/maincontroller.lua
  lua/buffon/ui/help.lua
  lua/buffon/ui/mainwindow.lua
  tests/config_spec.lua
Labels: release

#121 feat: replaces spaces by tabs
  .editorconfig
  CONTRIBUTING.md
  README.md
  lua/buffon/buffer.lua
  lua/buffon/bufferslist.lua
  lua/buffon/config.lua
  lua/buffon/init.lua
  lua/buffon/log.lua
  lua/buffon/maincontroller.lua
  lua/buffon/page.lua
  lua/buffon/pagecontroller.lua
  lua/buffon/storage.lua
  lua/buffon/ui/help.lua
  lua/buffon/ui/mainwindow.lua
  lua/buffon/ui/window.lua
  lua/buffon/utils.lua
Labels: documentation, enhancement
